#!/usr/bin/env python

import sys
import argparse

from killerbee import *

# Command line main function
if __name__ == '__main__':
    # Command-line arguments
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-f', '--channel', '-c', action='store', dest='channel', required=True, type=int, default=11)
    parser.add_argument('-i', '--iface', '--dev', action='store', dest='devstring')
    args = parser.parse_args()

    # try-except block to catch keyboard interrupt.
    try:
        kb = KillerBee(device=args.devstring)
        kb.reactive_jammer_on(args.channel)
    except KeyboardInterrupt:
        print 'Shutting down'

